# Site settings
title: Yeongki Baek
twitter_username:
name: Yeongki Baek

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/yeongkib
 - title: LinkedIn
   url: https://www.linkedin.com/
   
#Any buzzword skills you want to include
skills:
 - C/C++(14, 17)
 - STL
 - FmodEX
 - MPR
 - OpenGL
 - GLFW
 - Deferred Shading
 - GLSL

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: 

#Work experience is required
roles:
 - title: Intern
   start: Mar 2010
   end: Aug 2010
   employer: CobaltRay - Seoul, Korea
   description: .

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2018
   subject: Computer Science in Real-Time Interactive Simulation
   school: Digipen Institute of Technology (Redmond, WA)

#This section is optional (as is the image link below)
coursera: 

#List of interesting Github repo/projects to include - optional
github:
 - yeongkib/HOLD

#Stackoverflow flair is optional
stackoverflow:

#Mobile apps section is optional
apps:

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
   
