# Site settings
title: Yeongki Baek
twitter_username:
name: Yeongki Baek

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/yeongki
 - title: LinkedIn
   url: https://linkedin.com/in/yeongkib
resume:
 - title: Resume/CV
   url: resume.pdf

   
#Any buzzword skills you want to include
skills:
 - C/C++(14, 17)
 - STL
 - FmodEX
 - MPR
 - OpenGL
 - GLFW
 - PBR
 - Deferred Shading
 - GLSL

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: 

#Work experience is required
roles:
 - title: Information Technology Specialist
   start: Jan 2013
   end: Nov 2014
   employer: Republic of Korea Marine Corps - Marine 1st Div
   size: 
   description: 2 years military veteran who earned 3 commendations and awards for superior performance in academic, tactical and technical capacities. Promoted ahead of peers to mid-to-senior level supervisor in command of up to 40 soldiers. Earned highest marks in all leader evaluation reports, and recognized for mentoring and developing the best leaders. During that time, I developed and maintained a site to manage enlisted resources on the intranet from scratch. And established logistic analysis management information system.

 - title: Associate Programmer
   start: Mar 2010
   end: Aug 2010
   employer: CobaltRay - Seoul, Korea
   size: 
   description: Cobalt Ray Co. Ltd. engages in software and hardware development and manufacture. I developed a tool to sync sheet music to real audio while I was learning new API. It has helped content developers to create content more easily and quickly. 

#project is required
projects:
 - role: AI Programmer - Starcraft Broodwar
   start: May 2017
   end: Present
   short_description: A custom AI bot with influence map, BWAPI, C++
   size: Solo Project
   did1: Researched, evaluated, and designed the conceptual model for the real-time simulation game from scratch
   did2: Developed various data structures and algorithms to make dynamic strategies
   did3: Integrated 3rd party library (map analyzer), Implemented custom pathfinder for the efficient movement
   did4: Examined the performance and optimized the system <b>300%</b> faster than former version by special data structure
   did5:
   
 - role: Graphics and Gameplay Programmer - Alaska Roll
   start: Sep 2016
   end: Apr 2017
   short_description: 3D quarter view multishooter - Custom C++ 3D engine
   size: 5 Person Team
   did1: Built a custom deferred shading based graphic render system using OpenGL which increases performance and stability
   did2: Led three programmers with task prioritization and delegation to best meet deadlines and milestone expectations
   did3: Assisted physics programmer to build collision system for better performance; O(n^3) to O(n^2)
   did4: Designed the rule base and programmed multiple aspects including AI and basic gameplay
   did5:

 - role: Gameplay Programmer, Designer - AMAZE
   start: Sep 2010
   end: Apr 2011
   short_description: 2D puzzle shooter - Custom C++ 2D engine
   size: 7 Person Team
   did1: Created a tool that allows designer to procedurally generate tile map without difficulty
   did2: Constructed particle engine, text rendering systems and UI, increasing creative visual appeal in the game
   did3: Wrote scalable gameplay components allowing designers to iterate on 3 bosses and 8 enemies across 5 levels
   did4: Designed, implemented, tested, and iterated on the gameâ€™s tutorial alongside the lead designer
   did5:

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2018
   subject: Computer Science in Real-Time Interactive Simulation (ABET, CAC Accredited Program)
   school: Digipen Institute of Technology (Redmond, WA)
 - level: Minor
   date:
   subject: Mathematics
   school:

#This section is optional (as is the image link below)
coursera: 

#List of interesting Github repo/projects to include - optional
github:
 - yeongki/HOLD

#Stackoverflow flair is optional
stackoverflow:

#Mobile apps section is optional
apps:

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
   
