# Site settings
title: Yeongki Baek
twitter_username:
name: Yeongki Baek

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/yeongkib
 - title: LinkedIn
   url: https://www.linkedin.com/
resume:
 - title: Resume/CV
   url: https://github.com/yeongkib/yeongkib.github.io/blob/master/resume.pdf

   
#Any buzzword skills you want to include
skills:
 - C/C++(14, 17)
 - STL
 - FmodEX
 - MPR
 - OpenGL
 - GLFW
 - Deferred Shading
 - GLSL

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: 

#Work experience is required
roles:
 - title: Associate Programmer
   start: Mar 2010
   end: Aug 2010
   employer: CobaltRay - Seoul, Korea
   size: 
   description: Cobalt Ray Co. Ltd. engages in software and hardware development and manufacture. I developed a tool to sync sheet music to real audio while I was learning new API. It has helped content developers to create content more easily and quickly. 

 - title: Computer Technician
   start: Jan 2013
   end: Nov 2014
   employer: Republic of Korea Marine Corps - Marine 1st Div
   size: 
   description: Developed and maintained a site to manage enlisted resources on the intranet from scratch. And established logistic analysis management information system.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2018
   subject: Computer Science in Real-Time Interactive Simulation
   school: Digipen Institute of Technology (Redmond, WA)
 - level: Minor
   date:
   subject: Mathematics
   school:

#This section is optional (as is the image link below)
coursera: 

#List of interesting Github repo/projects to include - optional
github:
 - yeongkib/HOLD

#Stackoverflow flair is optional
stackoverflow:

#Mobile apps section is optional
apps:

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
   
